window.N2 = window.N2 || {};
N2.I18N={
 en:{
  ui:{newGame:'NEW GAME',continue:'CONTINUE',language:'LANGUAGE',english:'ENGLISH',swedish:'SVENSKA',satchel:'SATCHEL',close:'CLOSE',swim:'SWIM',dive:'DIVE',climb:'CLIMB',quest:'QUEST',save:'GAME SAVED',part1:'PART II',title:'FINDING NO-NO-NAMOSH II',subtitle:'THE LOST STAR',demoEnd:'CHAPTER COMPLETE',demoMsg:'Crystalwater Grotto is complete. The road to Azure Coast is now open.'},
  areas:{apt:'Aya’s Apartment',hall:'Apartment Hallway',rose:'Rosewood in the Rain',green1:'Greenhaven Road',green2:'Greenhaven Valley',green3:'Old Irrigation Fields',riverTown:'Riverside Settlement',inlet:'Training Inlet',riverCross:'The Great River',grotto1:'Crystalwater Grotto — Entrance',grotto2:'Crystalwater Grotto — Floodgate Hall',grotto3:'Crystalwater Grotto — Sunken Passage',grotto4:'Crystalwater Grotto — Star Chamber',grotto5:'Crystalwater Grotto — Escape Channel'},
  quests:{count:'Something feels wrong. Count the kittens.',hall:'Follow the tiny wet paw prints into the hallway.',rose:'Follow Namosh’s trail out of Rosewood.',green:'Cross Greenhaven and find where Namosh went.',abdullah:'Follow the marked trail south with Abdullah.',river:'Reach the Great River.',sami:'Speak with Sami the Fisherman about crossing the river.',lesson:'Complete Sami’s swimming lesson.',cross:'Cross the Great River and follow Namosh’s trail.',grotto:'Find a way through Crystalwater Grotto.',flood1:'Activate the first floodgate.',flood2:'Use the raised water to reach the second floodgate.',dive:'Find a way through the deep underwater passage.',star:'Investigate the Five-Point Star chamber.',escape:'Escape the flooding grotto.',complete:'The road to Azure Coast is open.'},
  items:{starShard:['Star Fragment','A warm, faintly glowing fragment found beside the kitten’s trail.'],whiteStone:['White-Stone Trail Mark','Abdullah marked the correct path through Greenhaven.'],herbs:['Greenhaven Herbs','Fresh herbs for Umm Zaynab.'],swimBadge:['River Knot','Sami’s little rope knot — proof Aya completed the swimming lesson.'],diveGoggles:['Old Diving Goggles','Repaired diving goggles from Crystalwater Grotto.'],crystal:['Cooling Crystal','A bright blue crystal humming with cold water energy.']},
  names:{Aya:'Aya',Namosh:'Namosh',Abdullah:'Abdullah',Netra:'Professor Netra',Sami:'Sami the Fisherman',Ahmed:'Ahmed',Farah:'Farah',UmmZ:'Umm Zaynab',Narrator:'Narrator'},
  dialog:{
   intro:[['Narrator','Several months after the first adventure, Aya’s apartment has become considerably louder.'],['Aya','One... two... three... four...'],['Aya','Namosh.'],['Aya','Where is number five?'],['Narrator','Namosh freezes. Her ears turn toward the apartment door.'],['Narrator','Thunder rolls outside. The lights flicker.'],['Narrator','Namosh scratches at the door — not playfully.'],['Aya','Oh absolutely not. We already did this.'],['Narrator','Aya opens the door. Tiny wet kitten paw prints lead down the hallway.'],['Namosh','MRRROW!'],['Narrator','Namosh bolts after them.'],['Aya','NAMOSH!']],
   hall:[['Narrator','The kitten’s tiny paw prints continue through the hallway and down the stairs.'],['Aya','At least this time I know why she is running.']],
   rose:[['Narrator','Rain has washed most of the tracks away, but fresh scratches mark the gate leading out of Rosewood.'],['Aya','She went toward Greenhaven. Of course she did.']],
   ahmed:[['Ahmed','Aya? I saw Namosh fly past like a tiny black-and-white storm.'],['Aya','Was she alone?'],['Ahmed','I saw smaller tracks too. They lead toward the old irrigation fields.']],
   farah:[['Farah','A cat scared my chickens half to death.'],['Aya','Black and white?'],['Farah','Very angry-looking.'],['Aya','That is new. She is usually only judgmental.']],
   ummz:[['Umm Zaynab','Habibti, the storm has made the lower road muddy. Take the high path by the herbs.'],['Aya','Thank you. If you see Namosh, tell her I am furious and worried in equal amounts.']],
   abdullah:[['Abdullah','Aya? Professor Netra sent me to check the strange activity near the observatory.'],['Aya','One of Namosh’s kittens is missing. Namosh went after her.'],['Abdullah','Then I am coming with you.'],['Aya','You say that now.'],['Abdullah','I remember the mountain.'],['Narrator','Abdullah places small white stones where the trail forks.']],
   shard:[['Narrator','Something glows faintly beside the kitten’s paw prints.'],['Aya','That definitely was not here yesterday.'],['Netra','Aya? Abdullah sent me the image. Do not lose that fragment. The marking matches the Old Observatory.'],['Aya','I am currently prioritizing a missing kitten.'],['Netra','I know. Unfortunately, I think the two problems may be connected.']],
   sami1:[['Sami','Aya! Back at the river?'],['Aya','I need to get across. Namosh and one of her kittens did somehow.'],['Sami','That current will carry you halfway to the sea if you enter it like that.'],['Aya','Helpful.'],['Sami','Come to the inlet. I will teach you how to read the current.']],
   sami2:[['Sami','Good. Keep your body with the current, not against it.'],['Aya','I crossed a mountain before learning this?'],['Sami','Apparently.'],['Narrator','Aya can now SWIM in marked water.']],
   grottoEnter:[['Narrator','The river current pulls Aya toward a crack beneath the waterfall.'],['Abdullah','AYA!'],['Narrator','They disappear beneath the white water and surface inside a vast glowing cavern.'],['Aya','I knew learning to swim would somehow make today worse.']],
   flood1:[['Narrator','Aya pulls the ancient lever. Deep inside the cave, stone gates grind open.'],['Narrator','Water rises through the lower chamber.'],['Abdullah','That opened a route above us.']],
   flood2:[['Narrator','The second floodgate shudders into place. A submerged tunnel becomes visible below.'],['Aya','Please tell me we are not going underwater.'],['Abdullah','We are definitely going underwater.']],
   goggles:[['Narrator','Abdullah finds a pair of old sealed goggles in a maintenance chest.'],['Abdullah','The rubber is somehow intact.'],['Aya','That sentence is not reassuring.'],['Narrator','Aya can now DIVE in deep water. Press B while swimming to dive or surface.']],
   star:[['Narrator','At the bottom of the grotto stands a colossal stone emblem. Five points surround a hollow center.'],['Netra','That is not a paw symbol. It is part of a five-site system.'],['Netra','The Old Observatory is one point. Crystalwater Grotto is another.'],['Aya','And the other three?'],['Netra','I do not know yet. But all five point toward Mount Qamar.'],['Aya','That sounds suspiciously like a future problem.']],
   escape:[['Narrator','The final mechanism cracks. Water begins pouring through the chamber.'],['Abdullah','RUN!'],['Aya','Finally, an instruction I understand.']],
   end:[['Narrator','Aya and Abdullah burst from the grotto into daylight. Far beyond the river, the road bends toward a bright blue coast.'],['Netra','The next marked site may lie beyond Azure Coast.'],['Aya','First I find Namosh. Then we discuss ancient civilizations.'],['Abdullah','You know those are probably the same quest now.'],['Aya','I was hoping you would not say that.']]
  }
 },
 sv:{
  ui:{newGame:'NYTT SPEL',continue:'FORTSÄTT',language:'SPRÅK',english:'ENGLISH',swedish:'SVENSKA',satchel:'VÄSKA',close:'STÄNG',swim:'SIMMA',dive:'DYK',climb:'KLÄTTRA',quest:'UPPDRAG',save:'SPELET SPARAT',part1:'DEL II',title:'FINDING NO-NO-NAMOSH II',subtitle:'DEN FÖRLORADE STJÄRNAN',demoEnd:'KAPITLET KLART',demoMsg:'Crystalwater Grotto är avklarad. Vägen mot Azure Coast är nu öppen.'},
  areas:{apt:'Ayas lägenhet',hall:'Trapphuset',rose:'Rosewood i regnet',green1:'Vägen till Greenhaven',green2:'Greenhaven Valley',green3:'Gamla bevattningsfälten',riverTown:'Flodbyn',inlet:'Träningsviken',riverCross:'Den stora floden',grotto1:'Crystalwater Grotto — Ingång',grotto2:'Crystalwater Grotto — Slussalen',grotto3:'Crystalwater Grotto — Den sjunkna gången',grotto4:'Crystalwater Grotto — Stjärnkammaren',grotto5:'Crystalwater Grotto — Flyktkanalen'},
  quests:{count:'Något känns fel. Räkna kattungarna.',hall:'Följ de små våta tassavtrycken ut i trapphuset.',rose:'Följ Namoshs spår ut från Rosewood.',green:'Ta dig genom Greenhaven och hitta vart Namosh tog vägen.',abdullah:'Följ den markerade leden söderut tillsammans med Abdullah.',river:'Ta dig till den stora floden.',sami:'Prata med Sami the Fisherman om hur ni ska ta er över floden.',lesson:'Klara Samis simlektion.',cross:'Korsa den stora floden och följ Namoshs spår.',grotto:'Hitta en väg genom Crystalwater Grotto.',flood1:'Aktivera den första slussen.',flood2:'Använd det stigande vattnet för att nå den andra slussen.',dive:'Hitta en väg genom den djupa undervattensgången.',star:'Undersök kammaren med den femuddiga stjärnan.',escape:'Fly från den översvämmade grottan.',complete:'Vägen mot Azure Coast är öppen.'},
  items:{starShard:['Stjärnfragment','Ett varmt, svagt glödande fragment som låg bredvid kattungens spår.'],whiteStone:['Vit stenmarkering','Abdullah markerade rätt väg genom Greenhaven.'],herbs:['Greenhaven-örter','Färska örter till Umm Zaynab.'],swimBadge:['Flodknut','Samis lilla repknut — bevis på att Aya klarade simlektionen.'],diveGoggles:['Gamla dykglasögon','Reparerade dykglasögon från Crystalwater Grotto.'],crystal:['Kylkristall','En klarblå kristall som vibrerar av kall vattenenergi.']},
  names:{Aya:'Aya',Namosh:'Namosh',Abdullah:'Abdullah',Netra:'Professor Netra',Sami:'Sami the Fisherman',Ahmed:'Ahmed',Farah:'Farah',UmmZ:'Umm Zaynab',Narrator:'Berättare'},
  dialog:{
   intro:[['Narrator','Flera månader efter det första äventyret har Ayas lägenhet blivit betydligt mer högljudd.'],['Aya','En... två... tre... fyra...'],['Aya','Namosh.'],['Aya','Var är nummer fem?'],['Narrator','Namosh stelnar till. Öronen vrids mot ytterdörren.'],['Narrator','Åskan mullrar utanför. Lamporna blinkar.'],['Narrator','Namosh krafsar på dörren — inte lekfullt.'],['Aya','Åh absolut inte. Det här har vi redan gjort.'],['Narrator','Aya öppnar dörren. Små våta tassavtryck leder genom trapphuset.'],['Namosh','MRRROW!'],['Narrator','Namosh rusar efter dem.'],['Aya','NAMOSH!']],
   hall:[['Narrator','Kattungens små tassavtryck fortsätter genom trapphuset och nerför trapporna.'],['Aya','Åtminstone vet jag varför hon springer den här gången.']],
   rose:[['Narrator','Regnet har sköljt bort nästan alla spår, men färska rivmärken syns på grinden ut från Rosewood.'],['Aya','Hon gick mot Greenhaven. Självklart gjorde hon det.']],
   ahmed:[['Ahmed','Aya? Jag såg Namosh rusa förbi som en liten svartvit storm.'],['Aya','Var hon ensam?'],['Ahmed','Jag såg mindre spår också. De leder mot de gamla bevattningsfälten.']],
   farah:[['Farah','En katt skrämde nästan ihjäl mina höns.'],['Aya','Svartvit?'],['Farah','Såg väldigt arg ut.'],['Aya','Det är nytt. Vanligtvis är hon bara dömande.']],
   ummz:[['Umm Zaynab','Habibti, stormen har gjort den nedre vägen lerig. Ta den övre vägen vid örterna.'],['Aya','Tack. Om du ser Namosh, säg att jag är lika delar arg och orolig.']],
   abdullah:[['Abdullah','Aya? Professor Netra skickade mig för att undersöka den konstiga aktiviteten vid observatoriet.'],['Aya','En av Namoshs kattungar är borta. Namosh sprang efter henne.'],['Abdullah','Då följer jag med dig.'],['Aya','Det säger du nu.'],['Abdullah','Jag minns berget.'],['Narrator','Abdullah lägger små vita stenar där leden delar sig.']],
   shard:[['Narrator','Något glöder svagt bredvid kattungens tassavtryck.'],['Aya','Det där låg definitivt inte här igår.'],['Netra','Aya? Abdullah skickade bilden. Tappa inte fragmentet. Märkningen matchar det gamla observatoriet.'],['Aya','Just nu prioriterar jag en försvunnen kattunge.'],['Netra','Jag vet. Tyvärr tror jag att problemen hänger ihop.']],
   sami1:[['Sami','Aya! Tillbaka vid floden?'],['Aya','Jag måste över. Namosh och en av kattungarna lyckades tydligen.'],['Sami','Den strömmen skickar dig halvvägs till havet om du går i så där.'],['Aya','Hjälpsamt.'],['Sami','Kom till viken. Jag lär dig läsa strömmen.']],
   sami2:[['Sami','Bra. Följ strömmen med kroppen, kämpa inte rakt emot den.'],['Aya','Jag korsade ett berg innan jag lärde mig det här?'],['Sami','Tydligen.'],['Narrator','Aya kan nu SIMMA i markerat vatten.']],
   grottoEnter:[['Narrator','Flodströmmen drar Aya mot en spricka under vattenfallet.'],['Abdullah','AYA!'],['Narrator','De försvinner under det vita vattnet och kommer upp i en enorm lysande grotta.'],['Aya','Jag visste att simkunskaper på något sätt skulle göra dagen värre.']],
   flood1:[['Narrator','Aya drar i den gamla spaken. Djupt inne i grottan börjar stenportar mala.'],['Narrator','Vattnet stiger genom den nedre kammaren.'],['Abdullah','Det öppnade en väg ovanför oss.']],
   flood2:[['Narrator','Den andra slussen skakar på plats. En nedsänkt tunnel blir synlig nedanför.'],['Aya','Säg inte att vi ska under vattnet.'],['Abdullah','Vi ska definitivt under vattnet.']],
   goggles:[['Narrator','Abdullah hittar ett par gamla täta glasögon i en underhållskista.'],['Abdullah','Gummit är på något sätt fortfarande helt.'],['Aya','Den meningen gör mig inte lugnare.'],['Narrator','Aya kan nu DYKA i djupt vatten. Tryck B medan du simmar för att dyka eller gå upp till ytan.']],
   star:[['Narrator','På grottans botten står ett enormt stenemblem. Fem spetsar omger ett tomt centrum.'],['Netra','Det där är ingen tassymbol. Det är en del av ett system med fem platser.'],['Netra','Det gamla observatoriet är en punkt. Crystalwater Grotto är en annan.'],['Aya','Och de andra tre?'],['Netra','Det vet jag inte än. Men alla fem pekar mot Mount Qamar.'],['Aya','Det låter misstänkt mycket som ett framtida problem.']],
   escape:[['Narrator','Den sista mekanismen spricker. Vatten forsar in i kammaren.'],['Abdullah','SPRING!'],['Aya','Äntligen en instruktion jag förstår.']],
   end:[['Narrator','Aya och Abdullah kastar sig ut ur grottan i dagsljuset. På andra sidan floden böjer vägen av mot en klarblå kust.'],['Netra','Nästa markerade plats kan ligga bortom Azure Coast.'],['Aya','Först hittar jag Namosh. Sedan pratar vi om gamla civilisationer.'],['Abdullah','Du vet att det förmodligen är samma uppdrag nu.'],['Aya','Jag hoppades att du inte skulle säga det.']]
  }
 }
};
N2.lang='en';
N2.t=function(path){const parts=path.split('.');let v=N2.I18N[N2.lang];for(const p of parts)v=v?.[p];return v??path};
N2.say=function(rows){return rows.map(([n,t])=>[N2.t('names.'+n),t])};
